Update for Laravel 7
Kolovious/MeliSocialite pull request #12
Opened 2020-07-04 15:55 UTC by wesleydeveloper

2020-07-04 16:21 UTC, kolovious requested changes

2020-07-04 16:21 UTC, kolovious commented on src/MeliSocialite.php
> +        return $this->buildAuthUrlFromBase(MeliManager::$AUTH_URL['MLB'] . '/authorization', $state);
Me gustaria quitar MLB y dejarlo por una configuracion para que sea configurable segun el pais que quieren operar.

2020-07-07 12:29 UTC, wesleydeveloper commented on src/MeliSocialite.php
> +        return $this->buildAuthUrlFromBase(MeliManager::$AUTH_URL['MLB'] . '/authorization', $state);
se passar o pais no construtor 

services.meli.country

criar uma variavel estatica para guardar essa infor

protected static $COUNTRY

e um método para devolver a url pronta

public static function getAuthUrlWithCountry()
    {
        return self::$AUTH_URL[self::$COUNTRY];
    }

o que acha?

2020-07-07 13:16 UTC, wesleydeveloper commented on src/MeliSocialite.php
> +        return $this->buildAuthUrlFromBase(MeliManager::$AUTH_URL['MLB'] . '/authorization', $state);
Não foi uma boa idéia, hêhê

2020-07-07 22:35 UTC, kolovious approved these changes

2020-07-07 22:35 UTC, merged